export type { IManagedFields } from "./common.js";
export type {
  User,
  Role,
  UserStatus,
  IUser,
  IRegistrationInput,
  IRegistrationResult,
} from "./user.js";
export type {
  ConfigParameterType,
  ReportSeverity,
  ApiProviderStatus,
  AlertComparisonOperator,
  AlertNotificationMethod,
  AlertSeverityLevel,
  AlertMetric,
  IConfigRegistrationField,
  IConfigParameter,
  IConfigText,
  IConfigBoostFactor,
  IConfigVehicleType,
  IConfigListingDuration,
  IConfigReportReason,
  IConfigChatAction,
  IConfigModerationRule,
  IConfigApiProvider,
  IConfigAlert,
  IAlertEvent,
  IApiCallLog,
  IConfigCache,
  SeoPageType,
  IConfigSeoTemplate,
  AuditSeverity,
  IAuditTrailEntry,
} from "./config.js";
export type {
  ConsentDecision,
  IConfigConsentType,
  IUserConsent,
  IConsentInput,
} from "./consent.js";
export type { IDecodedToken, IUserContext, IAuthState, IAuthUser, ISessionConfig } from "./auth.js";
export type {
  RoleCode,
  PermissionCode,
  IRole,
  IUserRole,
  IPermission,
  IRolePermission,
  IConfigFeature,
} from "./rbac.js";
export type {
  ProfileCompletionBadge,
  IConfigProfileField,
  IProfileUpdateInput,
  IIncompleteField,
  IProfileCompletionResult,
  IPublicSellerProfile,
  ISellerRating,
} from "./profile.js";
export type {
  ExportStatus,
  AnonymizationStatus,
  IDataExportRequest,
  IAnonymizationRequest,
  IDataExportRequestResult,
  IExportDownloadResult,
  IAnonymizationRequestResult,
  IAnonymizationResult,
  IDataExportSection,
  IDataExportContent,
} from "./rgpd.js";
export type {
  KpiMetric,
  IKpiValue,
  ITrafficSource,
  IDashboardKpis,
  ITrendDataPoint,
  IKpiCardConfig,
} from "./dashboard.js";
export type {
  LegalDocumentKey,
  ILegalDocument,
  ILegalDocumentVersion,
  ILegalAcceptance,
} from "./legal.js";
export type {
  AdapterProviderMeta,
  AdapterError,
  VehicleLookupRequest,
  VehicleLookupResponse,
  EmissionRequest,
  EmissionResponse,
  RecallRequest,
  RecallCampaign,
  RecallResponse,
  CritAirLevel,
  CritAirRequest,
  CritAirResponse,
  VINTechnicalRequest,
  VINTechnicalResponse,
  HistoryRequest,
  HistoryMileageRecord,
  HistoryAccident,
  HistoryResponse,
  ValuationRequest,
  ValuationResponse,
  PaymentStatus,
  PaymentRequest,
  PaymentResponse,
  WebhookEventType,
  WebhookEvent,
} from "./adapters.js";
export type {
  CertifiedFieldResult,
  ApiSourceStatusState,
  ApiSourceStatus,
  IdentifierType,
  AutoFillRequest,
  AutoFillResponse,
  AutoFillResult,
  ICertifiedField,
  IApiCachedData,
} from "./autofill.js";
export type {
  IListing,
  FieldStatus,
  ListingFieldState,
  UpdateListingFieldResult,
  SaveDraftResult,
  ICertifiedFieldHistory,
  IListingPhoto,
  PhotoMimeType,
  UploadPhotoResult,
  ReorderPhotosInput,
} from "./listing.js";
export type {
  ScoreSuggestion,
  VisibilityScoreResult,
  VisibilityScoreInput,
  VisibilityScoreWeights,
} from "./visibility-score.js";
